name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Access Google Service
        run: echo '${{secrets.GOOGLE_SERVICES_JSON}}' > ./app/google-service.json

      - name: Access KAKAO Key
        env:
          KAKAO_API_KEY: ${{secrets.KAKAO_API_KEY}}
        run: echo KAKAO_API_KEY=\"$KAKAO_API_KEY\" > ./local.properties

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Check ktlint format
        run: ./gradlew ktlintCheck


